# Generated by Django 5.0.2 on 2024-03-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
